# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            CV/DL
tagline:          'CV/DL'
description:      'A blog for CV/DL'
url:              http://sangdv.github.io
baseurl:          /

author:
  name:           'Sang Dinh'
  url:            https://users.soict.hust.edu.vn/sangdv/

paginate:         5

# Custom vars
version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
